### ISSUE TITLE
Is there any other way to download the AITOD dataset, such as Baidu Netdisk ？

### ISSUE THREAD

**Issue by Icecream-blue-sky** [jwwangchn/AI-TOD#22]
I find it difficult to download AITOD dataset with onedrive. Is there any other way to download the AITOD dataset, such as Baidu Netdisk ？

**Comment by Icecream-blue-sky** [comment]
AI-TOD dataset can be easily downloaded from here (https://www.cvmart.net/dataSets/detail?tabType=1&id=361).

**Comment by todesti2** [comment]
> AI-TOD数据集可以从这里轻松下载（https://www.cvmart.net/dataSets/detail?tabType=1&id=361）。

你好 请问下载了这个之后就不用按readme操作了吗？还是说这个能代替哪一步骤呢？

**Comment by Chasel-Tsui** [comment]
> > AI-TOD数据集可以从这里轻松下载（[https://www.cvmart.net/dataSets/detail?tabType=1&id=361）。](https://www.cvmart.net/dataSets/detail?tabType=1&id=361%EF%BC%89%E3%80%82)
> 
> 你好 请问下载了这个之后就不用按readme操作了吗？还是说这个能代替哪一步骤呢？

你好，是的，下载完就不用按照readme操作，直接使用图片和标签即可。因为版权原因，这个github无法直接公开xview相关的图片。

**Comment by huxinkai** [comment]
> > AI-TOD数据集可以从这里轻松下载（[https://www.cvmart.net/dataSets/detail?tabType=1&id=361）。](https://www.cvmart.net/dataSets/detail?tabType=1&id=361%EF%BC%89%E3%80%82)
> 
> 你好 请问下载了这个之后就不用按readme操作了吗？还是说这个能代替哪一步骤呢

> AI-TOD dataset can be easily downloaded from here (https://www.cvmart.net/dataSets/detail?tabType=1&id=361).

你好，我下了百度网盘中的AI-TOD数据集，测试集没有标签啊，该如何测试性能呢？

**Comment by huxinkai** [comment]
> > > AI-TOD数据集可以从这里轻松下载（[https://www.cvmart.net/dataSets/detail?tabType=1&id=361）。](https://www.cvmart.net/dataSets/detail?tabType=1&id=361%EF%BC%89%E3%80%82)
> > 
> > 
> > 你好 请问下载了这个之后就不用按readme操作了吗？还是说这个能代替哪一步骤呢？
> 
> 你好，是的，下载完就不用按照readme操作，直接使用图片和标签即可。因为版权原因，这个github无法直接公开xview相关的图片。

你好，我下了百度网盘中的AI-TOD数据集，测试集没有标签啊，该如何测试性能呢？

**Comment by huxinkai** [comment]
> > AI-TOD数据集可以从这里轻松下载（[https://www.cvmart.net/dataSets/detail?tabType=1&id=361）。](https://www.cvmart.net/dataSets/detail?tabType=1&id=361%EF%BC%89%E3%80%82)
> 
> 你好 请问下载了这个之后就不用按readme操作了吗？还是说这个能代替哪一步骤呢？

你好，我下了百度网盘中的AI-TOD数据集，测试集没有标签啊，该如何测试性能呢？

**Comment by Chasel-Tsui** [comment]
你好，github提供的下载链接里面有test set的完整标签

**Comment by huxinkai** [comment]
> 你好，github提供的下载链接里面有test set的完整标签

A Guide on Generating AI-TOD问题 #33
您好，您能帮忙看下这个问题吗？谢谢

**Comment by ado901** [comment]
I can't download the dataset from cvmart. Is there another way?
