### ISSUE TITLE
如何支持其他框架的aitod数据集适配

### ISSUE THREAD

**Issue by yuhua666** [jwwangchn/AI-TOD#26]
博士您好！我对这份数据集做出的贡献很感兴趣，但我只找到了mmdetection对这份数据集的适配支持。
我希望能在其他代码框架下训练这份数据集，例如faster-rcnn.pytorch，我该怎么做呢，您可以指导一下，给我一个方向吗？因为源代码只支持了coco和voc数据集，而aitod在指标上略有差异。

**Comment by Chasel-Tsui** [comment]
我没有用过faster-rcnn.pytorch这个框架，不过猜测主要修改的地方应该包括:nms前后保留的预测数量，每张图片最多检测数量、评估指标(安装aitodpycocotools)

**Comment by yuhua666** [comment]
您好，我尝试了很久修改代码以使其适应，但没有成功。
我想将aitod转换成voc格式，faster-rcnn.pytorch找个框架的voc训练比较方便，但coco部分代码是针对2014数据集的，比较难修改。
请问我将aitod转换成voc格式的想法可行吗？因为我注意到aitod的json和coco的json里的标注还是不太一样的，希望能得到您的指导，如果可行的话，还望您提供一些思路上的指导，感谢！
