### ISSUE TITLE
Access Denied for AITOD Dataset Download via OneDrive Link

### ISSUE THREAD

**Issue by Ark1a** [jwwangchn/AI-TOD#36]
I am trying to download the AITOD dataset, but I'm encountering an "access denied" error when using the provided OneDrive link. Could you please provide guidance or a solution for this issue?

**Comment by NicolasDrapier** [comment]
same problem

**Comment by Chasel-Tsui** [comment]
Hi, I have uploaded the files to the Google Drive, please check the following link to see whether it is accessible: https://drive.google.com/drive/folders/1uNY_rcOO5LrWibXRY6l2dvqSbK6xikJp?usp=sharing

**Comment by NicolasDrapier** [comment]
That's perfect, I was able to download the dataset
Thank you @Chasel-Tsui

**Comment by Ark1a** [comment]
Cool.
Thanks for your help, @Chasel-Tsui !
