### ISSUE TITLE
How to download the dataset

### ISSUE THREAD

**Issue by chandlerbing65nm** [jwwangchn/AI-TOD#8]
I can't see the link to the dataset. When will it be available? Thanks

**Comment by Chasel-Tsui** [comment]
> I can't see the link to the dataset. When will it be available? Thanks

The AI-TOD dataset and this repository are undergoing a comprehensive update, they will be available soon!

**Comment by chandlerbing65nm** [comment]
Thanks! when is the tentative date of release of updates?

**Comment by Chasel-Tsui** [comment]
We have re-opened the download link and updated the user guide.
